# Generated by Django 2.2 on 2019-04-29 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Anonym', max_length=10)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Mood')),
            ],
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='pphoto',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pmodel',
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
        migrations.DeleteModel(
            name='PModel',
        ),
        migrations.DeleteModel(
            name='PPhoto',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
