# Generated by Django 2.2 on 2019-05-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190507_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='del_pass',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
